### ISSUE TITLE
Request for the source code of "Grip"

### ISSUE THREAD

**Issue by zhimin-wang** [tcsantini/EyeRecToo#3]
Hi, Santini.

Recently, I try to find the implementation of Grip in your EyeRec and EyeRecToo. I also found the project web of eyerectoo was moved to: https://www.hci.uni-tuebingen.de/research/Engagement%20&%20Interaction/eyerectoo.html.
However, I can't find the source code of "Get a Grip". I read the code of gaze estimation in EyeRecToo but I think it may not be the implementation. Could you share the source code? 

Thanks for your contributions to the community. Looking forward to your reply : )

**Comment by ArmstrongYang** [comment]
您好，已经收到邮件，我会尽快处理给予回复，谢谢！

**Comment by Tawaana19** [comment]
Hey @ArmstrongYang I am looking for the code for Get a Grip as well. Can you please share it with me as well. Thanks in advance.

**Comment by tcsantini** [comment]
Sorry about the project being moved, I have no control over links in the university's website.

For Grip, please check the Gitlab repository -- it's in the dev branch, which hasn't been pushed to Github because I haven't setup Git LFS here.

Grip is implemented by the [GazeVectorBinocularPolyFit](https://es-git.cs.uni-tuebingen.de/santini/EyeRecToo/-/blob/08f72c525a9b7ce4a1a77c26b52cd5afba6d8dcb/EyeRecToo/src/gaze-estimation/GazeVectorBinocularPolyFit.cpp#L17). You might be interested in [this commit](https://es-git.cs.uni-tuebingen.de/santini/EyeRecToo/-/commit/08f72c525a9b7ce4a1a77c26b52cd5afba6d8dcb) as well.

**Comment by Tawaana19** [comment]
Thank you so much for the quick response.

**Comment by zhimin-wang** [comment]
I get it. Thank you very much. 

Good luck to you!

**Comment by yuxinma4life** [comment]
Hello! It would be great if I could have the source code for Grip implementation. Thank you!

**Comment by ArmstrongYang** [comment]
您好，已经收到邮件，我会尽快处理给予回复，谢谢！
